
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.1.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: requirements-txt-fixer
  - id: trailing-whitespace

 - repo: https://github.com/psf/black
  rev: 19.10b0
  hooks:
  - id: black

 - repo: https://github.com/mgedmin/check-manifest
  rev: "0.42"
  hooks:
  - id: check-manifest

 - repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.780
  hooks:
  - id: mypy
    files: src
